### PR TITLE
fixed rapid flicker of prompt_contenner

### PR DESCRIPTION
**Pull request by JonJee**
image

Hello.
When the mouseover action in prompt image is occurred, the prompt_contenner was flickered rapidly. So I added css code `pointer-events: none;`. Additionally, I also added `background-color: #fff;`, because it looks overlapping.

thanks!

### CODE REVIEW

**Comment by lakshmang123** [comment]
Good

**Comment by mugo55** [comment]
Very good

**Comment by wanzrush29** [comment]
Good,,

**Comment by LKBHATI71** [comment]
Best of ideas good way---

**Pull request merged**
